server:
  port: 5003

spring:
  application:
    name: SUBMISSION-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    password: Bn19c0248@
    username: root
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/submission_service
    driver-class-name: com.mysql.cj.jdbc.Driver
